### ISSUE TITLE
Ups. An error occurred: 1

### ISSUE THREAD

**Issue by CymricNPG** [stefanrinderle/sonar-softvis3d-plugin#16]
Not very informative, can you provide a better error message? The stacktrace was:
( sonar-softVis3D-plugin-0.3.4.jar, SonarQube 5.1.2 )

015.11.18 16:03:37 INFO  web[d.r.s.w.v.VisualizationWebserviceHandler] Create layout for 56043_CITY_20_1
2015.11.18 16:03:37 INFO  web[d.r.s.w.v.VisualizationWebserviceHandler] Start layout calculation for snapshot 56043, metrics 1 and 20
2015.11.18 16:03:37 ERROR web[d.r.s.w.AbstractWebserviceHandler] 1
java.lang.ArrayIndexOutOfBoundsException: 1
        at de.rinderle.softvis3d.dao.ScmCalculationService.extractScmInfo(ScmCalculationService.java:76) ~[na:na]
        at de.rinderle.softvis3d.dao.ScmCalculationService.getDifferentAuthors(ScmCalculationService.java:47) ~[na:na]
        at de.rinderle.softvis3d.dao.DaoService.getMaxScmInfo(DaoService.java:96) ~[na:na]
        at de.rinderle.softvis3d.layout.bottomup.SnapshotVisitorBean.<init>(SnapshotVisitorBean.java:95) ~[na:na]
        at de.rinderle.softvis3d.layout.bottomup.SnapshotVisitorBean$$FastClassByGuice$$15239f61.newInstance(<generated>) ~[na:na]
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) ~[na:na]
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60) ~[na:na]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[na:na]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254) ~[na:na]
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978) ~[na:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024) ~[na:na]
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974) ~[na:na]
        at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:632) ~[na:na]
        at com.sun.proxy.$Proxy54.create(Unknown Source) ~[na:na]
        at de.rinderle.softvis3d.layout.LayoutProcessor.process(LayoutProcessor.java:43) ~[na:na]
        at de.rinderle.softvis3d.VisualizationProcessor.visualize(VisualizationProcessor.java:53) ~[na:na]
        at de.rinderle.softvis3d.webservice.visualization.VisualizationWebserviceHandler.createLayout(VisualizationWebserviceHandler.java:122) ~[na:na]
        at de.rinderle.softvis3d.webservice.visualization.VisualizationWebserviceHandler.handleRequest(VisualizationWebserviceHandler.java:87) ~[na:na]
        at de.rinderle.softvis3d.webservice.AbstractWebserviceHandler.handle(AbstractWebserviceHandler.java:39) ~[na:na]
        at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:84) [sonar-server-5.1.2.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:425) [jruby-complete-1.7.9.jar:na]

**Comment by stefanrinderle** [comment]
Hey,

thank you for trying my SonarQube plugin and for this error report. The issue is within the first approach to load scm infos like authors count and commits within the last X days. I did some coding there a week ago and I assume, that this should not occur with the current snapshot version of the plugin.

If that's not the case - I will have to try to reproduce the issue with the 0.3.4 first...

I attached you the current plugin jar file. As its not allowed to upload jar files here, please rename the file from .gif to .jar first.

![sonar-softvis3d-plugin-0 3 5-snapshot](https://cloud.githubusercontent.com/assets/2418659/11252164/f84aa5a4-8e34-11e5-804c-90a0f3cca7d6.gif)
